const items = [
    { name: '.30-06 Box', amount: 5 ,rate: 'uncommon', command: '#SpawnItem Cal30-06_Ammobox_Closed', img: 'https://scum.online/wp-content/uploads/scumimages/Cal_30-06_Ammobox.png'  },
    { name: '.45 ACP Box', amount: 5 ,rate: 'uncommon', command: '#SpawnItem Cal_45_AmmoboxClosed', img: 'https://scum.online/wp-content/uploads/scumimages/Cal_45_Ammobox.png'  },
    { name: '5.56x45mm Box', amount: 5 , rate: 'uncommon', command: '#SpawnItem Cal_5_56x45mm_Ammobox', img: 'https://scum.online/wp-content/uploads/scumimages/Cal_5_56x45mm_Ammobox.png'  },
    { name: '7.62x39mm Box', amount: 5 ,rate: 'uncommon', command:'#SpawnItem Cal_7_62x39mm_Ammobox', img: "https://scum.online/wp-content/uploads/scumimages/Cal_7_62x39mm_Ammobox.png" },
    { name: '7.62x54mmR Box', amount: 5 ,rate: 'uncommon', command:'#SpawnItem Cal_7_62x54mmR_Ammobox', img: "https://scum.online/wp-content/uploads/scumimages/Cal_7_62x54mmR_Ammobox.png" },
    { name: '.9mm Box', amount: 5 ,rate: 'uncommon', command:'#SpawnItem Cal_9mm_AmmoboxClosed', img: "https://scum.online/wp-content/uploads/scumimages/Cal_9mm_Ammobox.png" },
    { name: 'Aeroplane Repair Kit', amount: 2 ,rate: 'common', command:'#Spawnitem Aeroplane_Repair_Kit', img: "https://static.wikia.nocookie.net/scum_gamepedia_en/images/3/39/Airplane_Repair_Kit.png" },
    { name: 'AK15', amount: 1 ,rate: 'rare', command:'#SpawnItem BPC_Weapon_AK15', img: "https://static.wikia.nocookie.net/scum_gamepedia_en/images/9/94/AK15.png" },
    { name: 'AK47', amount: 1 ,rate: 'uncommon', command:'#SpawnItem BP_Weapon_AK47', img: "https://scum.online/wp-content/uploads/scumimages/BP_Weapon_AK47.png" },
    { name: 'Armor tactical Vest Black', amount: 2 ,rate: 'uncommon', command:'#SpawnItem Armor_Tactical_Vest_03', img: 'https://scum.online/wp-content/uploads/scumimages/Armor_Tactical_Vest_03.png' },
    { name: 'AWM', amount: 1 ,rate: 'uncommon', command:'#spawnitem BP_Weapon_AWM', img: 'https://static.wikia.nocookie.net/scum_gamepedia_en/images/c/ce/AWM.png' },
    { name: 'AWP', amount: 1 ,rate: 'uncommon', command:'#spawnitem BP_Weapon_AWP', img: 'https://static.wikia.nocookie.net/scum_gamepedia_en/images/7/78/AWP.png' },
    { name: 'Emergency Bandage Pack', amount: 2 ,rate: 'common', command:'#spawnItem Emergency_Bandage_Big', img: 'https://static.wikia.nocookie.net/scum_gamepedia_en/images/5/54/Emergency_Bandage_Pack.png' },
    { name: '.50mm BMG Box', amount: 3 ,rate: 'epic', command:'#spawnitem Cal_50BMG_Ammobox', img: 'https://static.wikia.nocookie.net/scum_gamepedia_en/images/9/9c/.50_BMG_Box.png' },
    { name: 'Car Repair Kit', amount: 2 ,rate: 'common', command:'#spawnItem Car_Repair_Kit', img: 'https://static.wikia.nocookie.net/scum_gamepedia_en/images/c/c7/Car_Repair_Kit.png' },
    { name: 'Weapon Cleaning Kit', amount: 3 ,rate: 'uncommon', command:'#spawnItem Weapon_Cleaning_Kit', img: 'https://scum.online/wp-content/uploads/scumimages/Weapon_Cleaning_Kit.png' },
    { name: 'Ghillie Suit Jacket Desert', amount: 1 ,rate: 'common', command:'#spawnitem Ghillie_Suit_Jacket_Desert', img: 'https://i.imgur.com/CU7luRb.png' },
    { name: 'Ghillie Suit Jacket', amount: 1 ,rate: 'common', command:'#spawnitem Ghillie_Suit_Jacket', img: 'https://static.wikia.nocookie.net/scum_gamepedia_en/images/f/fc/Ghillie_Suit_Jacket_Black.png' },
    { name: 'Medical Gloves', amount: 5 ,rate: 'common', command:'#spawnitem Medical_Glove', img: 'https://static.wikia.nocookie.net/scum_gamepedia_en/images/d/d6/Medical_Gloves_All.jpg' },
    { name: 'Insulating Rubber Gloves Black', amount: 5 ,rate: 'common', command:'#spawnitem Electrician_Glove_03', img: 'https://static.wikia.nocookie.net/scum_gamepedia_en/images/1/1e/Electrician_Gloves_Yellow.png' },
    { name: 'Grenade', amount: 2 ,rate: 'uncommon', command:'#spawnitem BP_Frag_Grenade', img: 'https://static.wikia.nocookie.net/scum_gamepedia_en/images/f/fb/Grenade.png' },
    { name: 'Key Card', amount: 1 ,rate: 'epic', command:'#spawnitem BP_KeyCard', img: 'https://static.wikia.nocookie.net/scum_gamepedia_en/images/2/25/Scum_Key_card.png' },
    { name: 'Key Card', amount: 3 ,rate: 'legendary', command:'#spawnitem BP_KeyCard', img: 'https://static.wikia.nocookie.net/scum_gamepedia_en/images/2/25/Scum_Key_card.png' },
    { name: 'Lock Protection Advanced', amount: 2 ,rate: 'epic', command:'#spawnitem Lock_Security_Lvl3', img: 'https://i.imgur.com/P0xSyjt.png' },
    { name: 'Enforced Lock', amount: 3 ,rate: 'epic', command:'#spawnitem Lock_Item_Advanced', img: 'https://static.wikia.nocookie.net/scum_gamepedia_en/images/a/ab/Enforced_Lock.png' },
    { name: 'M1 Garand', amount: 1 ,rate: 'rare', command:'#spawnitem BP_Weapon_M1_Garand', img: 'https://static.wikia.nocookie.net/scum_gamepedia_en/images/5/5f/M1_Garand.png' },
    { name: 'M16A4', amount: 1 ,rate: 'uncommon', command:'#spawnitem BP_Weapon_M16A4', img: 'https://static.wikia.nocookie.net/scum_gamepedia_en/images/e/ea/M16.png' },
    { name: 'M82A1', amount: 1 ,rate: 'legendary', command:'#spawnitem BP_Weapon_M82A1', img: 'https://static.wikia.nocookie.net/scum_gamepedia_en/images/2/27/M82A1.png' },
    { name: 'MK18', amount: 1 ,rate: 'rare', command:'#spawnitem BP_Weapon_MK18', img: 'https://static.wikia.nocookie.net/scum_gamepedia_en/images/f/f2/MK18.png' },
    { name: 'MP5', amount: 1 ,rate: 'uncommon', command:'#spawnitem BP_Weapon_MP5', img: 'https://static.wikia.nocookie.net/scum_gamepedia_en/images/d/d5/MP5.png' },
    { name: 'Beef Stew MRE', amount: 5 ,rate: 'common', command:'#spawnitem MRE_Stew', img: 'https://static.wikia.nocookie.net/scum_gamepedia_en/images/3/37/MRE_Stew.png' },
    { name: 'Pickup Black', amount: 1 ,rate: 'epic', command:'#spawnvehicle BP_Pickup_01_B', img: 'https://static.wikia.nocookie.net/scum_gamepedia_en/images/e/ec/Pickup_B.png' },
    { name: 'Phoenix Tears', amount: 2 ,rate: 'epic', command:'#spawnitem Phoenix_Tears', img: 'https://i.imgur.com/Q76wpqq.png' },
    { name: 'RPK-74', amount: 1 ,rate: 'rare', command:'#spawnitem BPC_Weapon_RPK-74', img: "https://static.wikia.nocookie.net/scum_gamepedia_en/images/a/ad/RPK.png" },
    { name: 'Screwdriver', amount: 2 ,rate: 'rare', command:'#spawnitem Screwdriver', img: "https://static-cdn.jtvnw.net/jtv_user_pictures/f02c8bb8-6d2a-4fd1-8f9d-facdc0cade79-profile_banner-480.png" },
    { name: 'SUV Black', amount: 1 ,rate: 'epic', command:'#spawnvehicle BP_SUV_01_E', img: "https://static.wikia.nocookie.net/scum_gamepedia_en/images/4/4f/SUV_E.png" },
    { name: 'SVD', amount: 1 ,rate: 'rare', command:'#spawnitem BP_Weapon_SVD_Dragunov', img: "https://static.wikia.nocookie.net/scum_gamepedia_en/images/3/33/SVD.png" },
    { name: 'Tool Box', amount: 3 ,rate: 'common', command:'#spawnItem Tool_Box', img: "https://static.wikia.nocookie.net/scum_gamepedia_en/images/1/10/Tool_Box.png" },
    { name: 'UMP 45', amount: 1 ,rate: 'uncommon', command:'#spawnitem BPC_Weapon_UMP45', img: "https://static.wikia.nocookie.net/scum_gamepedia_en/images/e/e4/UMP_45.png" },
    { name: 'VHS2', amount: 1 ,rate: 'uncommon', command:'#spawnitem BP_Weapon_VHS2_Rail', img: "https://static.wikia.nocookie.net/scum_gamepedia_en/images/9/92/VHS2.png" },
    { name: 'VHS BG', amount: 1 ,rate: 'rare', command:'#spawnitem BP_Weapon_VHS_BG', img: "https://static.wikia.nocookie.net/scum_gamepedia_en/images/2/26/VHS-BG.png" },
]

export default items